### PR TITLE
Added pressure convertor in the conversion tools

### PR DESCRIPTION
**Pull request by RahulSahOfficial**
I have added the pressure convertor webpage to this utility project 
preview

I have add 1 folder and 4 files 

1 folder (pressure) inside conversion tool folder

4 files in the pressure folder
1. pressure.html
2. pressure.css
3. pressure.js
4. preview.png

### CODE REVIEW

**Comment by shubham2704** [comment]
@RahulSahOfficial Awesome work on this one 🎉. One of the nicest PR ✔. keep Contributing and Happy Coding👩‍💻✌

**Comment by RahulSahOfficial** [comment]
> @RahulSahOfficial Awesome work on this one 🎉. One of the nicest PR ✔. keep Contributing and Happy Coding👩‍💻✌

Hey @shubham2704  why don't you make the website **public** so we can use it in out daily life.
Like this (https://rahulsahofficial.github.io/memorygame)


And I found that in most of the convertor pages the contributors just copied and pasted the links of index
so in almost all the pages the navbar is not working **(as the links are broken**)
I am making the issue ,  assign that work to me  👍

**Comment by shubham2704** [comment]
> > @RahulSahOfficial Awesome work on this one 🎉. One of the nicest PR ✔. keep Contributing and Happy Coding👩‍💻✌
> 
> Hey @shubham2704 why don't you make the website **public** so we can use it in out daily life.
> Like this (https://rahulsahofficial.github.io/memorygame)
> 
> And I found that in most of the convertor pages the contributors just copied and pasted the links of index
> so in almost all the pages the navbar is not working **(as the links are broken**)
> I am making the issue , assign that work to me 👍

Don't open the issue it has already been done in another branch, but not merged on the main one. It will be merged in few days and the site will go live.

**Comment by RahulSahOfficial** [comment]
Can you update my links in the contribution section

- Mail : developersah@gmail.com
- Twitter :  https://twitter.com/developer_sah
- Github : Its correct

Thanks in advance 👍

**Pull request merged**
