### PR TITLE
[Feature] Improve the design of the index.html

### PR DESCRIPTION
**Pull request by negarjf**
## Title
Improve the design of the index.html

Closes Issue #5

## Number of files/folder added
2 folders and 3 files

```
- assets [folder]
-- syles [folder]
--- style.css

- favicon.ico 
- .gitignore
```

## Changes made
- The whole design of the `index.html` has been changed (Navbar, Hero Section, List, Footer)
- Add some custom styles
- Add an animation
- Provide search input for future implementation
- Add favicon
- Add title and meta tags
- Add `.gitignore` file

## I have:
 
- [X] Read contibuting.md
- [X] Followed all the guidelines
- [ ] Linked my tool to the index.html file
- [ ] updated readme.md

### CODE REVIEW

**Comment by negarjf** [comment]
@shubham2704 I wasn't sure where should I add my name as a contributor since my changes are related to the index page and tools. Could you please let me know if there is a good place for that?

**Comment by shubham2704** [comment]
> @shubham2704 I wasn't sure where should I add my name as a contributor since my changes are related to the index page and tools. Could you please let me know if there is a good place for that?

@negarjf you can add your name to index.html. Or it would be very nice if you can also work on issue #18

**Comment by shubham2704** [comment]
@negarjf Very nice job on this PR 💯. Great Job 🎉.
Would be very happy if you  continue contributing.

And Lastly did the issue got solved for the invalid PR. As you can check the topic of repository already have `hacktoberfest` and `hacktoberfest2020` mentioned in it. Sorry for the inconvenience. And i think that's no more a issue now so you can keep contributing. ✌

**Comment by negarjf** [comment]
@shubham2704 Thank you so much 😊 
I will try my best to continue my contribution.

Yes, thank you for the fix. Now the PRs are counted on the Hacktoberfest profile.

**Pull request merged**
