### PR TITLE
Added temperture conversion 

### PR DESCRIPTION
**Pull request by programmerraja**
fixed issue #13 

## Title
  Temperture conversion

## Number of files/folder added 
- added temperture.html ,temperture.css ,temperture.js in conversionTool/temperture
## changes made
- changes index.html nav and readme file 

## I have;
-  [x]  Read contibuting.md
-  [x] Followed all the guidelines 
-  [x] Linked my tool to the index.html file
-  [x] updated readme.md

## preview of the work

tempconv

### CODE REVIEW

**Comment by shubham2704** [comment]
@programmerraja  we have updated our guidelines now you don't have to add any changes to index.html and contributors.html as this rule was causing many conflicts . so please remove the changes you made in index.html. and then your PR will be ready to merge.

**Review by shubham2704 — CHANGES_REQUESTED** [review]
@programmerraja we have updated our guidelines now you don't have to add any changes to index.html and contributors.html as this rule was causing many conflicts . so please remove the changes you made in index.html. and then your PR will be ready to merge.

**Comment by shubham2704** [comment]
@programmerraja good work 🥇 . Read the new guidelines:
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by programmerraja** [comment]
@shubham2704  ok bro i will do it ✌️

**Comment by programmerraja** [comment]
@shubham2704  bro can you take look my new pull request #58

**Pull request closed without merging**
