### PR TITLE
added scrrenshot of Ui in readme and made chnages in styling of index…

### PR DESCRIPTION
**Pull request by vp4140**
After the changes in styling, the page looks visually appealing and attractive.

### CODE REVIEW

**Comment by vp4140** [comment]
> After the changes in styling, the page looks visually appealing and attractive.

home

**Comment by daplo** [comment]
Why would you repeat so many styles? Add it to the class in CSS.

**Comment by vp4140** [comment]
> Why would you repeat so many styles? Add it to the class in CSS.



> Why would you repeat so many styles? Add it to the class in CSS.

Added styling to an independent css file

**Comment by vp4140** [comment]
> > Why would you repeat so many styles? Add it to the class in CSS.
> 
> > Why would you repeat so many styles? Add it to the class in CSS.
> 
> Added styling to an independent css file

Are you not going to merge my files???

**Pull request closed without merging**
