### PR TITLE
Added Quadratic Equation Solver to mathematical tools

### PR DESCRIPTION
**Pull request by RahulSahOfficial**
I have added the Quadratic Equation Solver webpage to this utility project

preview

I have add 1 folder and 4 files

1 folder (quadratic) inside mathematicaltools folder

4 files in the resistance folder

quadratic.html
quadratic.css
quadratic.js
preview.png

**For Contribution**  (Update my contribution details Its incomplete)
Github : https://github.com/RahulSahOfficial
Twitter : https://twitter.com/developer_sah
Email : developersah@gmail.com

### CODE REVIEW

**Comment by shubham2704** [comment]
@RahulSahOfficial I have labeled your PR as Hacktoberfest-accepted, The PR will be merged shortly

**Comment by RahulSahOfficial** [comment]
Mr @shubham2704  what is hacktober fest 

And i am **new in github** i need **help** from you
Like how to **update my forkked repo with your original  repo** and few  more doubts

**Comment by shubham2704** [comment]
> Mr @shubham2704 what is hacktober fest
> 
> And i am **new in github** i need **help** from you
> Like how to **update my forkked repo with your original repo** and few more doubts

- Hacktober fest is a month long open source competition. where you have to make contribution to other github repository. and you can read more about the competetion here : https://hacktoberfest.digitalocean.com/ .  You can also get free T-Shirt by completing 4 valid PR's (only valid PR"s are counted towards winnig the T-Shirt. you can read there FAQ section to know what is valid PR)

- you can use below commands to update your forked repo. 
```
# Add the remote, call it "upstream":

git remote add upstream https://github.com/whoever/whatever.git

# Fetch all the branches of that remote into remote-tracking branches,
# such as upstream/main:

git fetch upstream

# Make sure that you're on your main branch:

git checkout main

# Rewrite your main branch so that any commits of yours that
# aren't already in upstream/main are replayed on top of that
# other branch:

git rebase upstream/main
```

**Comment by shubham2704** [comment]
> Mr @shubham2704 what is hacktober fest
> 
> And i am **new in github** i need **help** from you
> Like how to **update my forkked repo with your original repo** and few more doubts

And thank you for asking the question really appreciate it. Feel free to ask more and keep contributing.✌🎉

**Comment by RahulSahOfficial** [comment]
@shubham2704  in my account it shows 4 of 4 pull request it's showing mature timing in all 4 pull request 
What's the next step
Are you on Instagram ?

**Comment by shubham2704** [comment]
> @shubham2704 in my account it shows 4 of 4 pull request it's showing mature timing in all 4 pull request
> What's the next step
> Are you on Instagram ?

- Mature time is the 14 days time period in which Hacktober fest team review your PR's validity
- Yes you can follow me here : https://www.instagram.com/nano_python/

**Comment by shubham2704** [comment]
@RahulSahOfficial You really design the page so good 🎉✔

**Pull request merged**
