### PR TITLE
Added The Currency Converter Tool

### PR DESCRIPTION
**Pull request by Asies23**
#3 
### Added Currency Converter

- Added One Folder [currency](conversionTools/currency) with 3 files
- Made changes to the [Index.html](Index.html) file 
- Made changes to the [Readme.md](Readme.md) file

- [x] Read Contributing.md
- [x] Followed all Guidelines
- [x] Linked my tool to index.html file
- [x] Updated Readme.md

### CODE REVIEW

**Review by shubham2704 — CHANGES_REQUESTED** [review]
- Add the navbar and the footer as added in the index.html. 
- follow the design theme
-  add your name to the contributors.html

**Comment by shubham2704** [comment]
> * Add the navbar and the footer as added in the index.html.
> * follow the design theme
> * add your name to the contributors.html
@Asies23 Awesome job on the PR 💯 . Just make the requested changes and it will be ready to merge.

**Comment by shubham2704** [comment]
> > * Add the navbar and the footer as added in the index.html.
> > * follow the design theme
> > * add your name to the contributors.html
> >   @Asies23 Awesome job on the PR 💯 . Just make the requested changes and it will be ready to merge.

Calculator is also not working fix it

**Comment by Asies23** [comment]
@shubham2704 I cannot find the styles of the navbar and footer can you help me with that

**Comment by shubham2704** [comment]
@Asies23 you can find navbar in index.html file.

Also, our contributing guidelines have been changed, so please follow them before creating PR.
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository
- PR with any conflicts will `not be merged`
**Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Pull request merged**
