### PR TITLE
Compound Interest Calculator

### PR DESCRIPTION
**Pull request by OMEGAeNcore**
**Title :** Compound Interest Calculator
**Number of files/folder added :** 1 folder which includes 3 files
**Changes made :**
The html file includes simple web design that takes input data from the users through input boxes. The js file executes the compound interest calculation and helps display the calculated Accrued Amount and the compound interest generated.

I have:
- [x] Read contibuting.md
- [x]  Followed all the guidelines
- [x]  Linked my tool to the index.html file
- [ ]  updated readme.md
- [x]  add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created)
- [x]  provide below mentioned details if you want your name to be added in contributors.html
- [x]  mail, twitter, github profile link.

### CODE REVIEW

**Review by shubham2704 — COMMENTED** [review]
Good work @OMEGAeNcore just add the navbar as it is in the index.html file in your compoundinterestcalculator.html

**Comment by OMEGAeNcore** [comment]
Can I add the footer from the index.html file into compoundinterestcalculator.html as well, for mentioning my name for the tool?

**Comment by shubham2704** [comment]
@OMEGAeNcore we just had our new set of guidelines these are:
- Add navbar in your tool's html file. You can copy the navbar from index.html.
- Add screenshot of your tool in, PR message and also in the folder of your tool
- Before Making the PR Pull the latest changes that have been made to the repository

- **Note: Please Don't Make Any Changes In `index.html` AND `contributors.html` **

**Comment by shubham2704** [comment]
if your PR Doesn't conflict with any of above mentioned points then just let us know by commenting it here. else make the appropriate changes.

we are very sorry that the guidelines changed at this time.

**Comment by OMEGAeNcore** [comment]
I have made the necessary changes to the compoundinterestcalculator.html and it's corresponding css file as well.  There doesn't seem to be any conflict on my end. I have also added a screenshot of that. 

I was having some issues while pulling the latest repo changes, so I proceeded with the older version of repo itself. How should I proceed now?

**Comment by shubham2704** [comment]
@OMEGAeNcore I have labeled your PR as `hacktoberfest-accepted`  for now. it will be merged by Tomorrow. Happy Coding.💚 and 
Keep Contributing. 🥇 

- Also provide you mail,twitter and github profile. if you want us to add your name to the contributor page. we'll like to have you on our contributors page.

**Comment by OMEGAeNcore** [comment]
Thank you very much sir. If there is anything else required, I'll be happy to oblige.

Name: Ipshita Chakraborty
Email:  ipshita.chakraborty2211@gmail.com
GitHub: https://github.com/OMEGAeNcore

**Pull request merged**
