### PR TITLE
Add contributors page

### PR DESCRIPTION
**Pull request by purnima143**
###  **Title**
Add contributors.html page

Solved Issue #18 

### **Number of files/folder added**
2 files -contributors.html and contributor.css
1 img folder-3 images

 -assets [folder]
-- img [folder]
--- p1.jpg
---p2.jpg
---blank.jpg

 -assets[folder]
--styles[folder]
---contributor.css

 -contributors.html

### **Changes made**

- Designed contributors.html page, a page that contains the names of every contributor who have contributed to utility repo.

- Added contributor's social media links.

- Added Hover effect on profile image and social media icons.

- Linked the page in the footer section of the index.html page beside the Terms of Use.

- Page is totally responsive.

### I have:
 

- [x] Read contibuting.md

 

- [x] Followed all the guidelines

 

- [x] Linked my tool to the index.html file

 

- [ ] updated readme.md

### CODE REVIEW

**Review by shubham2704 — CHANGES_REQUESTED** [review]
- pleas Add screenshot of contributors.hmtl
- as we are unable to see the changes you made

**Comment by purnima143** [comment]
> * pleas Add screenshot of contributors.hmtl
> * as we are unable to see the changes you made

Okkay ,I will add it here.

**Comment by purnima143** [comment]
@shubham2704 
### Screenshot

**Comment by shubham2704** [comment]
@purnima143 Awesome work 🎉, looks really great. 🥇

**Comment by purnima143** [comment]
@shubham2704 Thanks for giving me this opportunity 🙂

**Comment by shubham2704** [comment]
- add your name too,  to the contributors.html. 
- and you can use this URL for adding your image == `https://github.com/purnima143.png` . (Useful Trick)

**Comment by purnima143** [comment]
> * add your name too,  to the contributors.html.
> * and you can use this URL for adding your image == `https://github.com/purnima143.png` . (Useful Trick)

@shubham2704 Done...Created PR

**Pull request merged**
