### PR TITLE
Added EMI Calculator

### PR DESCRIPTION
**Pull request by tusharv**
# Title
EMI Calculator 

# Number of files/folder added
- Added one folder `emi-calculator`
- Added two files `index.html` and `emi-calculator.png`

```
utility\financeTools\emi-calculator\index.html
utility\financeTools\emi-calculator\emi-calculator.png
```

# Changes made
- Added EMI Calculator in standalone HTML and used global style used in index.html
- Added JavaScript inline for ease of maintenance

# I have;

- [x]  Read contibuting.md 🆗 
- [x]  Followed all the guidelines 🆗 
- [ ]  updated readme.md ⛔ _Not Required_
- [ ]  add your name in the footer of your tool.html file (if you created length conversion tool then add your name to length.html file you created) ⛔ _Not Required_
- [ ]  provide below mentioned details if you want your name to be added in contributors.html ⛔ _Not Required_
- [ ]  mail, twitter, github profile link ⛔ _Not Required_

# Screen Shot
emi-calculator

# Comment
Reference : https://github.com/codeezzi/utility/issues/48

### CODE REVIEW

**Comment by shubham2704** [comment]
@tusharv Awesome work on this PR 🎉.
- But you forgot the directory structure. you need to create the folder of your tool.
- create the folder emiCalculator under financeTools and add your emi-calculator.html file to that folder
- your directory structure should look like this : `financeTools/emiCalculator /emi-calculator.html`

- Nice work just fix the requested changes and your PR will be merged. 🥇

**Review by shubham2704 — CHANGES_REQUESTED** [review]
@tusharv Awesome work on this PR 🎉.
- But you forgot the directory structure. you need to create the folder of your tool.
- create the folder emiCalculator under financeTools and add your emi-calculator.html file to that folder
- your directory structure should look like this : `financeTools/emiCalculator /emi-calculator.html`

- Nice work just fix the requested changes and your PR will be merged. 🥇

**Comment by tusharv** [comment]
Done.
Updated folder/file as `financeTools/emiCalculator/emi-calculator.html`

**Comment by shubham2704** [comment]
@tusharv  I have labeled your PR as hacktoberfest-accepted for now. it will be merged by Tomorrow. Happy Coding.💚 and
Keep Contributing. 🥇

**Comment by tusharv** [comment]
Sure @shubham2704 ,
I'll pickup more soon. but before that we need to fix template so that those who are contributing can use that template and all component will look uniform.

**Pull request merged**
